version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."

  build:
    commands:
      - echo "Build started on $(date)"
      - ls -al   
      - mkdir -p output
      - cp index.html output/

  post_build:
    commands:
      - echo "Build completed on $(date)"

artifacts:
  files:
    - output/index.html
