version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing NGINX
      - yum update -y
      - yum install nginx -y
      - mkdir -p /var/www/html

  build:
    commands:
      - echo Build started on $(date)
      - ls -la
      - cp ./index.html /var/www/html/   

  post_build:
    commands:
      - echo Post-build phase completed

artifacts:
  files:
    - /var/www/html/index.html
