version: 0.2

phases:
  install:
    commands:
      - echo "Installing NGINX on Amazon Linux 2"
      - yum update -y
      - yum install nginx -y
      - mkdir -p /var/www/html   

  build:
    commands:
      - echo "Build started on $(date)"
      - cp index.html /var/www/html/   

  post_build:
    commands:
      - echo "Post-build phase completed"

artifacts:
  files:
    - /var/www/html/index.html
